[versions]
agp = "8.8.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
room_version = "2.6.1"
rxandroid_version="3.0.2"
rxjava_version="3.1.8"
constraintlayout = "2.2.0"
hilt_version = "2.48"
hilt_compiler = "1.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
room = {group = "androidx.room", name = "room-runtime", version.ref = "room_version"}
room-annotation-processor = {group="androidx.room", name = "room-compiler", version.ref ="room_version"}
room-rxjava3 = {group = "androidx.room", name = "room-rxjava3", version.ref ="room_version"}
rxandroid = {group = "io.reactivex.rxjava3", name = "rxandroid", version.ref ="rxandroid_version"}
rxjava = {group = "io.reactivex.rxjava3", name = "rxjava", version.ref ="rxjava_version"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "hilt_compiler" }

